# Generated by Django 5.1.4 on 2024-12-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
