# Generated by Django 5.2.7 on 2025-11-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upipayment',
            name='wallet_id',
            field=models.CharField(max_length=100),
        ),
    ]
