# Generated by Django 5.2.7 on 2025-11-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_upipayment_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpayment',
            name='expiry_date',
            field=models.DateField(max_length=5),
        ),
    ]
