# Generated by Django 5.2.7 on 2025-11-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_creditpayment_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpayment',
            name='expiry_date',
            field=models.CharField(max_length=5),
        ),
    ]
