# Generated by Django 5.2.7 on 2025-11-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_creditpayment_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpayment',
            name='bank_acc_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='creditpayment',
            name='card_no',
            field=models.CharField(max_length=16),
        ),
    ]
